project_name: RLY08B-controller
builds:
  - binary: RLY08B
    goos:
      # - android
      - windows
      - darwin
      - linux
      # - dragonfly
      # - freebsd
      # - netbsd
      # - openbsd
      # - plan9
      # - solaris
    goarch:
      - 386
      - arm
      - amd64
      - ppc64
      - ppc64le
      - mips
      - mipsle
      - mips64
      - mips64le
archive:
  format: zip
  name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
snapshot:
  name_template: nightly